name: Build

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:

  linux:
    runs-on: ubuntu-20.04
    name: 🐧 Ubuntu 20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y gcc-10 g++-10 cmake make build-essential libcurl4-gnutls-dev

      - name: Build
        run: |
          mkdir -p build
          cd build
          CC=gcc-10 CXX=g++-10 cmake -DCMAKE_INSTALL_PREFIX="$PWD/install" ..
          make -j4 install

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ELF
          path: |
            build/install/*